import { Container } from "@/components/ui/container";
import { Eyebrow } from "@/components/ui/eyebrow";
import { getExperiences, getTechnologies } from "@/lib/data/public";
import { formatExperienceDateRange } from "@/lib/utils";

export default async function AboutPage() {
  const [experiences, technologies] = await Promise.all([getExperiences(), getTechnologies()]);
  return <div className="py-20 md:py-32"><Container size="narrow"><Eyebrow>About</Eyebrow><h1 className="mt-5 text-4xl md:text-6xl font-bold tracking-tight">I build the systems behind modern digital products.</h1><p className="mt-8 text-lg text-[#a1a1aa] leading-relaxed">Backend-focused full stack engineer working across reliable APIs, AI/RAG workflows, data systems, and product experiences.</p><div className="mt-16 grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#121316] p-6"><h2 className="text-xl font-semibold">Current focus</h2><p className="mt-3 text-[#a1a1aa] leading-relaxed">Production systems where strong contracts, useful observability, and clear domain architecture matter.</p></div><div className="rounded-2xl border border-white/10 bg-[#121316] p-6"><h2 className="text-xl font-semibold">Technical areas</h2><div className="mt-4 flex flex-wrap gap-2">{technologies.map((tech) => <span key={tech.name} className="rounded-md border border-white/10 bg-[#16171a] px-3 py-1.5 text-xs font-mono text-[#a1a1aa]">{tech.name}</span>)}</div></div></div><section className="mt-20"><Eyebrow>Timeline</Eyebrow><div className="mt-6 border-t border-white/10">{experiences.map((item) => <div key={item.id} className="grid gap-3 border-b border-white/10 py-7 md:grid-cols-[180px_1fr]"><span className="font-mono text-sm text-[#6c9cff]">{formatExperienceDateRange(item.start_date, item.end_date, item.current_role)}</span><div><h2 className="text-lg font-semibold">{item.role} · {item.company}</h2><p className="mt-2 text-sm text-[#a1a1aa]">{item.description}</p></div></div>)}</div></section></Container></div>;
}
